### ISSUE TITLE
NoSuchFieldError: LARGETURBINE_ACTIVE5 rendering Industrial Centrifuge

### ISSUE THREAD

**Issue by leagris** [draknyte1/MiscUtilities#1]
GT++ 1.4.1.2

Client crash with java.lang.NoSuchFieldError: LARGETURBINE_ACTIVE5 while rendering an Industrial Centrifuge block
[crash-2016-07-20_00.11.19-client.txt](https://gist.github.com/leagris/94000431035d7287e5864e6ac997cac7)

**Comment by draknyte1** [comment]
Should be fixed in 1.4.1.4

**Comment by leagris** [comment]
1.4.1.4 Still crashes
[crash-2016-07-20_10.16.17-client.txt](https://gist.github.com/leagris/497a6ac76a0d150aadc5c7d0572f2f42)

**Comment by draknyte1** [comment]
@leagris can you try the 1.4.2 build and let me know?

**Comment by leagris** [comment]
No longer crash with 1.4.2
